projects:
  AmplifyWikiNotes:
    schemaPath: /graphql/schema.graphql
    includes:
      - ../common/**/*.ts
      - ../common/graphql/aws_directives.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: types/API.ts
        docsFilePath: ./graphql
extensions:
  amplify:
    version: 3
